### ISSUE TITLE
From C# to Node: How to enable JavaScript debugger?

### ISSUE THREAD

**Issue by gerardog** [tjanczuk/edge#163]
Is there any way to enable the V8 debugger on a javascript code invoked from C# using edge? I want to debug the js code embedded inside a .NET application.

Thanks!

**Comment by tjanczuk** [comment]
The fix for this is to use the `EDGE_NODE_PARAMS` environment variable to pass whatever command line parameters you would normally invoke node.exe with, including `--debug`.

**Comment by tjanczuk** [comment]
This will ship as Edge.js 0.10.0

**Comment by joevolcano** [comment]
It would be better for me to have it more granular and be able to set it per call/v8thread. Instead of globally or at the process level. I will probably have to create a new  

public static Func<object,Task<object>> Func(string code, string node_params) 

that allows this to be passed in. and if not provided then defaults to the environment variable.

*could also use default to set node_param to null or empty or create overload.

**Comment by tjanczuk** [comment]
As far as I know the `--debug` switch is process-wide in Node itself and must be specified at the time the process starts. Behavior of Edge mimics this granularity.
