### ISSUE TITLE
Close C # library process

### ISSUE THREAD

**Issue by ykais** [tjanczuk/edge#180]
Hello! I want to ask you a question about how to close the C# library of edge after I call it

**Comment by ivoloshin** [comment]
I would like to know this as well. Basically I have a nodejs script that is long lived. If I issue a callback into it and then in node call process.exit(0) then I have weird exceptions in c# "An unhandled exception of type 'System.ExecutionEngineException' occurred in edge.node" I need a clean way to terminate my long running node process.

**Comment by tjanczuk** [comment]
Can you provide a repro?

**Comment by ivoloshin** [comment]
Unfortunately, it would take me a while to build it up, but, I found my solution, which was server-destroy npm package for closing express server objects that were holding on to their connections for a long time. Explicitly destroying the connections and closing the server and then calling the callback to c# now works as expected. Before it would hang, since node server was waiting for the connections to close.

However, it still appears that process.exit in node exits the whole process, including my c# app, which was certainly unexpected... I do not need to do this now since I found a graceful way to close the server connections. Alternatively, my next thing to do was to create a child process in node and see if process.exit would not bring the whole thing down, just the child process.

Anyway, thank you for your reply! Edge.JS so far has been outstanding and the docs are super helpful!

**Comment by tjanczuk** [comment]
Glad you solved it. For reference, here is an example of how to let your C# code prevent the node process from exiting even though there are no remaining node events to be processed or node listeners opened: https://github.com/tjanczuk/edge/blob/master/samples/111_clr_listener.js
