### ISSUE TITLE
problem loading Oracle.DataAccess

### ISSUE THREAD

**Issue by ghost** [tjanczuk/edge#212]
The file Oracle.DataAccess.dll, are in the same folder

undefined:1
(function (f, ctx) { return function (d, cb) { return f(d, cb, ctx); }; })
                                                      ^
Error: Could not load file or assembly 'Oracle.DataAccess, Version=4.
112.2.0, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies The system can't find the file specified,
    at <anonymous>:1:55
    at Object.<anonymous> (C:\xampp\htdocs\server\app.js:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by ckphilli2308** [comment]
In case anyone is still looking, I ran into the same symptoms. The code would compile with the reference, but then blow up at runtime. I changed my reference in VS to Oracle.ManagedDataAccess.dll (instead of Oracle.DataAccess.dll), set copy local to false, recompiled the .dll, replaced the file in my nodeproject and it ran perfectly. I still don't understand why it couldn't find the old one, but thought I'd share my remedy.
