### ISSUE TITLE
appSettings not available to C# code running in assembly invoked by Edge

### ISSUE THREAD

**Issue by DanielLarsenNZ** [tjanczuk/edge#221]
https://twitter.com/DanielLarsenNZ/status/536807830926278656

`System.Configuration.ConfigurationManager.AppSettings` does not contain settings in web.config when .NET assembly is invoked by Edge.

Code example: https://github.com/DanielLarsenNZ/Edge-AppSettings/blob/master/Edge-AppSettings-Service/AppSettingService.cs#L13

Demo: http://edgeappsettings.azurewebsites.net/

**Comment by jchannon** [comment]
I have the same problem too.

I'm currently in a position where I'm trying to host an Owin web server using mono on Linux for a production app but have come across socket leaks and constraints on .net based web servers so looked at connect-owin and all was working well until I came across this issue.

**Comment by ajbieber** [comment]
I am having a similar issue.

I am using a Node.js app hosted in IIS, which uses C# called by EdgeJS. This code instantiates a new a new object, and in that class's constructor we attempt to retrieve a Web.config key value. For some reason, we are not getting the value in the embedded C# code in EdgeJS. Is there something specific that needs to be done to correct this? Thanks!

**Comment by tjanczuk** [comment]
This is the situation: 

1. A node.js application hosted in IIS using iisnode behaves like a regular standalone Node.js application. iisnode acts as an HTTP reverse proxy that proxies requests from the IIS pipeline to the HTTP listener that the Node.js app has established over named pipes. 

2. Given that the Node.js application has no awareness of being called from IIS, neither does C# code embedded in it through Edge.js.

3. The C# code embedded in a Node.js app through Edge.js follows the configuration model of a regular, self-hosted console application. Specifically, it is attempting to load configuration from the `node.exe.config` file that must be located in the same directory as the `node.exe` executable that runs the process within which Edge.js hosts C# code. 

4. Since in a typical IIS+iisnode shared hosting environment the node.exe is installed globally on the machine, it is not feasible to place application-specific configuration values there. But...

5. iisnode has a configuration property called [nodeProcessCommandLine](https://github.com/tjanczuk/iisnode/blob/master/src/samples/configuration/iisnode.yml#L10-L13) which allows the application to specify an alternative location of the node executable (along with any custom arguments). This mechanism can be used to configure iisnode to start a node.exe from the application's `bin` folder (the node.exe must then become part of the application package). This in turn allows an application-specific `node.exe.config` file to be provided in the same directory.
