### ISSUE TITLE
Running JS from .NET on Non-windows

### ISSUE THREAD

**Issue by w0lph** [tjanczuk/edge#296]
In the documentation, it says that it's currently only available for Windows, any estimate for Linux and OSX?

**Comment by tjanczuk** [comment]
I have currently no plans or bandwidth to port "Node from .NET" support for non-Windows. I will be happy to consult with anyone willing to invest the time to submit a PR.

**Comment by romovs** [comment]
I started tinkering with "Node from .NET" on Linux yesterday so I figured to share my progress here just in case someone doing the same.

At the moment I am (almost) able to execute the Hello World example. Almost because the application doesn't terminate properly yet. I haven't had time to dig into this issue yet, though...

But overall what has been done so far is:

- node.js v0.12 patched to compile as a shared library + relevant changes to EdgeJs.cs. Also from a quick look there shouldn't be any issues making it work with v0.10.
- Embedded mono patched to allow reusing existing runtime when running from within one.
- Fixed file paths to be more Unix friendly.
