### ISSUE TITLE
electron (atom shell)

### ISSUE THREAD

**Issue by gtaranas** [tjanczuk/edge#302]
is there anyway to work with electron (http://electron.atom.io):

[Error: The edge module has not been pre-compiled for node.js version v0.12.7. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.]

**Comment by eblumenfeld** [comment]
I'm having the same issue with iojs.com

**Comment by DeRas** [comment]
I too experience this error:

Uncaught Error: The edge edge\lib\edge.js:19  module has not been pre-compiled for node.js version v2.3.1. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.

It's even printing out a high node.js version i dont have :) I tried different distributions of node.js, without any luck.

**Comment by romovs** [comment]
To make Edge.js work in Electron it needs to be compiled using the Electron headers -
https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

Also the module requires a little bit of patching. See the top five commits [here](https://github.com/oxygenhq/electron-edge).

**Comment by paulcbetts** [comment]
You can include the `edge-atom-shell` module which does the required patching - if you run it through `electron-rebuild` like the doc above says, it definitely works

**Comment by jimmcslim** [comment]
A well documented sample of using Electron, Edge and C# on Windows would be fantastic.

**Comment by EdAyers** [comment]
A good example I've found is [this](http://www.mylifeforthecode.com/electron-edge-dot-net-ermahgerd/). He also has some [other good posts](http://www.mylifeforthecode.com/category/electron/) explaining other things in electron. Sadly he doesn't post the source and if I follow along with the example I get that classic error that kills the javascript process; 
```
Uncaught Error: The edge module has not been pre-compiled for node.js version v2.3.1. 
You must build a custom version of edge.node. 
Please refer to https://github.com/tjanczuk/edge for building instructions. 
......
```
@paulcbetts has kindly made `electron-rebuild` which solves this problem by doing some node magic so that the rest of us don't need an intimate knowledge of native node module builds. Sadly there is an issue with this tool which may affect some people on windows. 
`electron-rebuild` - refuses to `npm install` on my windows machine. The relevant issue is [here](https://github.com/electronjs/electron-rebuild/issues/15). Hopefully this will be fixed or I will figure out what thing is preventing the package from working. 
I agree with @jimmcslim that a minimum example of getting these fantastic technologies to work would be hyper-useful.

**Comment by paulcbetts** [comment]
electron-rebuild won't work with edge.js at the moment, I've made a fork of edge.js that definitely does work on Windows with the currently released Electron.

**Comment by paulcbetts** [comment]
@EdAyers That bug is kind of a mess, I don't really understand what's going on there. Can you paste your issue there?

**Comment by WorldMaker** [comment]
It would be nice if there was an electron with edge prebuilt distribution...

**Comment by paulcbetts** [comment]
@WorldMaker `edge-atom-shell`

**Comment by WorldMaker** [comment]
@paulcbetts I was hoping for something more along the lines of an `electron-prebuilt` like fork that produced an `electron-edge.exe` that prebaked edge into an Electron.exe. That would probably be a nice thing to have.

(I can't seem to get `edge-atom-shell` to build at all and similar fork `electron-edge` builds but renames the module `electron-edge` which breaks compatibility with third party modules trying to require `edge`... Neither `electron-edge` nor `edge` proper seem to be building Native .NET support on my machine, yet .NET Core works, but won't load the COM component I seem to need... At this point it looks like my best bet is to `child-process` my way to a console app.)

**Comment by harivasista** [comment]
I am not able to get edge.js work with electron. I am having issues while doing 'electron-rebuild'. Could someone help me with this ?
