### ISSUE TITLE
cannot load edge module in electron app

### ISSUE THREAD

**Issue by qingbolove** [tjanczuk/edge#336]
App threw an error when running [Error: The edge module has not been pre-compiled for node.js version v5.0.0-pre. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.]

![image](https://cloud.githubusercontent.com/assets/10628904/10600252/dd374278-773b-11e5-8c86-81cc65bacba1.png)

**Comment by kexplo** [comment]
Try this "https://github.com/kexplo/electron-edge"

**Comment by oscarandreu** [comment]
I also have the same problem, even with the electron-edge fork.
I get this error with the regular edge
![image](https://cloud.githubusercontent.com/assets/1556393/10895196/c8c65c56-81aa-11e5-97de-553a6cf76c81.png)

And this error with the electron-edge fork 
![image](https://cloud.githubusercontent.com/assets/1556393/10895141/752f046c-81aa-11e5-8d39-92674ae4ca3e.png)

Some ideas will be very welcome because I need both edge and electron in this project.

**Comment by jhauser** [comment]
We solved this issue earlier this year via these npm packages: https://www.npmjs.com/package/electron-edge2

It is all a bit of a fiddle caused by the fork of Io.js from Node.js (electron was built on Io.js).  

Reportedly IO and Node have kissed and made up but we are not sure if this has helped bridge the gap between edge and electron. A task for us in January - to revisit electron apps running .NET c# code.

**Comment by radicalrob** [comment]
I have been having all of the aforementioned problems, but when I tried electron-edge2, I get the "not precompiled for node.js version v6.3.0".  But when I go into tools and try "build release 6.3.0" it can't find iojs.exe.  When I set the path to find it, the highest version of iojs is 3.3.1.  So I'm confused.  Does electron-edge2 currently work with node 6.3.0?  

Is there a branch or example somewhere that I can clone for edge in electron that just works?

**Comment by JoaoGabrielBrasil** [comment]
Me too.
I am with this problem!

node_modules\edge-cs is not packed into asar archive - contains executable code
node_modules\electron-edge is not packed into asar archive - contains executable code

What I do?

**Comment by arthurscheeren** [comment]
im currently using:
```
    "electron-debug": "^0.5.1",
    "electron-edge": "5.0.3-pre1",
    "electron-packager": "^5.1.1",
    "electron-prebuilt": "1.2.0",
    "electron-rebuild": "^1.0.0",
    "node": "6.3.0",
```
and it works fine here !
