### ISSUE TITLE
Marshalling Dictionnary<Enum, object> does not seem to work

### ISSUE THREAD

**Issue by niicojs** [tjanczuk/edge#487]
It seems that only string as key works, or am I missing something?

**Comment by pmoleri** [comment]
Hi, it seems that current implementation, for every `IDictionary` attempts to cast its keys to string and if it fails it does nothing. 

As a work around you could convert your Dictionary to <string, string>
```C#
using System.Linq;

source.ToDictionary(keyValue => keyValue.Key.ToString(), keyValue => keyValue.Value);
```

Perhaps Edge behavior could be changed so other keys are converted `.ToString()` instead of only attempt to cast them.

**Comment by nicoschmitt** [comment]
Thanks. The issue is that I don't manage source data. So I'll have to try to convert back and forth. And the risk of altering data is high.
What I'm trying to achieve us a plug-in system based is edge.
