### ISSUE TITLE
Edge.JS Could not load file or assembly or one of its dependencies

### ISSUE THREAD

**Issue by KashifSaleem224** [tjanczuk/edge#502]
i want to utilize DLLS in node.js using Edge.js. but i have faced an issue that Could not load file or assembly. one of its dependencies. The system cannot find the file specified.  please help 

this is my sample code which i used for it

this is c# method.
  public async Task<object> GetEmployees(object input)
        {
            return await context.Employees.ToListAsync();
        }
var edge = require('edge');

function apiResponseHandler(request, response) {
    return function (error, result) {
        if (error) {
            response.status(500).send({ error: error });
            return;
        }
        response.send(result);
    };
}

app.get('/api/employees', function (request, response) {

```
var getEmployeesProxy = edge.func({
    assemblyFile: "TestApp.dll",
    typeName: "TestApp.EmployeesOperations",
    methodName: "GetEmployees",
    references: [
        (path + "\\DLLS\\TestApp.dll")
    ]
}); 

getEmployeesProxy(null, apiResponseHandler(request, response));
```

});

please help me

**Comment by LsKs** [comment]
I have a very similar issue with latest Node 6 (v6.9.1, with manually compiled library), same code runs fine on Node 4 (any version).

Getting error:
`System.Runtime.InteropServices.COMException: Retrieving the COM class factory for component with CLSID {272371C6-6297-41D8-8BC7-3DDC991FBD39} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).`

**Comment by mateodelnorte** [comment]
I had this same problem using node v6.9.1. any version before or after seems to work correctly.
