### ISSUE TITLE
Building Edge for node v7.4.0

### ISSUE THREAD

**Issue by radencode** [tjanczuk/edge#537]
I am getting errors when I try to build the edge node, I run `build.bat release 7.4.0` and then what do I need to do after that?

**Comment by agracio** [comment]
It should work, make sure you have build tools installed as described in this issue: #https://github.com/tjanczuk/edge/issues/532. VS 2015 helps as well.
What errors are you getting?

**Comment by truefusion** [comment]
After spending several hours on it today, the solution (at least for me) turned out to be very simple (although, as linked, you can indeed compile it within VS). The problem for me is I have VS 2015 installed, but the build batch file kept configuring the project files for 2013. The fix was simple enough: Edit built.bat under the tools folder and change the line that says
`"%NODEEXE%" "%GYP%" configure build --msvs_version=2013 -%FLAVOR%`
to
`"%NODEEXE%" "%GYP%" configure build --msvs_version=2015 -%FLAVOR%`

Then you can finally run `build.bat release 7.4.0`

Hope this helps!

**Comment by radencode** [comment]
Thank you, I will give that a try after I get home from work.
