### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by bravomikekilo** [tjanczuk/edge#543]
seems there are no new changes for half year.

**Comment by ddaspit** [comment]
There have been several people that have asked the same question and there has been no response from the maintainer. It looks like this project needs to a new maintainer. There are two forks that seem to be actively improving Edge. @kexplo's electron-edge fork has been updated to work with the latest version of Electron. @agracio seems to be fixing various bugs on his fork. Maybe we should shift our focus to one of these forks. @agracio seems to be accepting PRs (see #541) so that fork sounds especially promising.

**Comment by dpolivy** [comment]
I know @tjanczuk has been very busy with other responsibilities, and has been looking for a new maintainer to take over responsibility for this project. I don't know where he ended up with that search, though.

**Comment by ddaspit** [comment]
It would be excellent if @tjanczuk could find a new maintainer if he is unable to continue working on it. There is clearly a demand for a project like Edge.js.

**Comment by SeanSnyders** [comment]
Yes, I'm also keen for this project to be kept alive. @agracio does seem to be active and looking at various issues.
I'm also up for contributing where I can as I have been trying to get Edge to play nicely with Electron and .Net Core (https://github.com/tjanczuk/edge/issues/544) as the existing repo does not.

**Comment by me0262** [comment]
I am also up for keeping this project alive. I too am running Electron (using Electron-Edge as a bridge).

I think I will start this out by updating the project.json files to their *.csproj equivalents, for the new SDKs.

**Comment by forensicsguy20012004** [comment]
Well I appears that this repo is not dead...as there has been an update for node 7.x.x. However, we will need a build for node 8.x.x.
