### ISSUE TITLE
.NET Core <-> .NET Framework?

### ISSUE THREAD

**Issue by benaadams** [tjanczuk/edge#553]
Could it be possible to host Core and Framework in same process and cross call between them?

**Comment by me0262** [comment]
I've used .dll files compiled in .NET Core and used them with Framework. This only works well on windows though. I've also had to include a very specific version of System.Runtime.dll with the dlls as well.
It's much more headache then it's worth.
NET Core 2.0 is out of the question. I would love to have it supported because I need XSL transformations in my Electron app.

**Comment by benaadams** [comment]
Thinking of a Core 2.0 app on Windows calling though to a Framework component on Framework runtime to fill gaps.

Was some grumpy for Windows devs recently about bits that Core 2.0 didn't support, making a switch runtimes more difficult (even though Core 2.0 have a high significance of the Framework apis; still some gaps for Windows only components)
