### ISSUE TITLE
Need build for Node 8.x.x

### ISSUE THREAD

**Issue by forensicsguy20012004** [tjanczuk/edge#574]
This is a request for a build for Node 8.x.x. In general the "group" should work out a process so when a new version of Node drops there will be a build for it. I am willing to do that work but would like some "help" or a "how to." I have no problem doing a PR when a new version of Node comes out but just do not know what steps I have to take in order to have a build for Node X.x.

**Comment by agracio** [comment]
Since early May PR merges there was no further activity on this repo, no other PRs have been merged and no further code changes were made. So not sure whether we will see any timely updates here.
I am still maintaining this fork: https://github.com/tjanczuk/edge/issues/541 although it moved to https://github.com/agracio/edge-js.
It has support for Node 8.1.2 and .Net Core along with some other bug fixes.

**Comment by wtchangdm** [comment]
I think [these steps](https://github.com/tjanczuk/edge#building-on-windows) should be enough.

don't forget to update versionMap variable in ./lib/edge.js though.

**Comment by forensicsguy20012004** [comment]
Thank you for the info
