### ISSUE TITLE
Need your help. How to get data in Json Format in a loop from Node.js to .NET (C#)?

### ISSUE THREAD

**Issue by waqasm78** [tjanczuk/edge#591]
I am new to Node.js and but I need to get data from Node.js to .NET and I found this package which is very helpful. 

I have the following code in Node.js which retrieve the npm packages information in Json format one by one and save it in a text file.

**********************************************
const ChangesStream = require('changes-stream');
const Request = require('request');
const Normalize = require('normalize-registry-metadata');
var fs = require('fs');

const db = 'https://replicate.npmjs.com';

var changes = new ChangesStream({
    db: db,
    include_docs: true
});

Request.get(db, function (err, req, body) {
    var end_sequence = JSON.parse(body).update_seq;
    changes.on('data', function (change) {
        if (change.seq >= end_sequence) {
            process.exit(0);
        }
        if (change.doc.name) {
            console.log(Normalize(change.doc));

            fs.appendFile('server.txt', JSON.stringify(change.doc), function (err) {
                if (err) return console.log(err);
            });
        }
    });
});

***************************************

Now I want this data to be returned to .NET  (C#) one by one instead of writing it text file. I believe it is very simple task but I am not sure how to do it. Please help me I will be very thankful to you for that.

**Comment by SwadX** [comment]
Some thing like this .. mentioned in the readme ?

How to: marshal data between C# and Node.js

Edge.js can marshal any JSON-serializable value between .NET and Node.js (although JSON serialization is not used in the process). Edge also supports marshalling between Node.js Buffer instance and a CLR byte[] array to help you efficiently pass binary data.

You can call .NET from Node.js and pass in a complex JavaScript object as follows:

var dotNetFunction = edge.func('Edge.Sample.dll');

var payload = {
    anInteger: 1,
    aNumber: 3.1415,
    aString: 'foo',
    aBoolean: true,
    aBuffer: new Buffer(10),
    anArray: [ 1, 'foo' ],
    anObject: { a: 'foo', b: 12 }
};

dotNetFunction(payload, function (error, result) { });

**Comment by therightstuff** [comment]
also, the fact that Edge .js returns associative arrays if and only if they’re correctly JSON formatted. I don’t recall seeing this documented anywhere, although it does make perfect sense (20/20 hindsight). So in order to return an associative array to Node.js, make sure to use a Dictionary object where the first element type is a string; if you want to send a list of usernames with their IDs, for example, you would either use

Dictionary<string, string>

with the ID cast to string for transmission or

Dictionary<string, int>

with the ID / username columns switched from their normal positions.
