### ISSUE TITLE
.Net Core 2.0 Support

### ISSUE THREAD

**Issue by joelsteventurner** [tjanczuk/edge#592]
Am trying to invoke a .net core 2.0 assembly , which it self references a .Net Frame work assembly (not .net net core)

I am getting an exception along the lines of unable to load "netstandard.dll".

Is .net core 2.0 currently supported ? If not, any idea when it would be supported?

**Comment by agracio** [comment]
Edge does not support any modern  .NET Core framework that uses .csproj files instead of project.json.
You can try `edge-js` fork that supports all new .NET Core frameworks including 2.0. .NET Core support did introduce an issue https://github.com/agracio/edge-js/issues/4, but it's not clear whether there will be any real life implications so try it out and see how well it works for you.
