### ISSUE TITLE
edge is not precompiled for Node version...

### ISSUE THREAD

**Issue by borgold** [tjanczuk/edge#620]
Impossible to find pre-compile instructions for module edge. I do not have all my life to look up everything on GitHub. I have never precompiled Node modules before. A straightforward instruction would be very helpful. Especially since you do not keep up with the latest version of Node released.

Please, provide instruction on how to precompile your module.

Even better, do precompile yourself, so people can rely on edge and modules dependent on it.

**Comment by tjanczuk** [comment]
Hello World!

**Comment by borgold** [comment]
I was trying to install windows-certs module. Unfortunately it depends on edge. this the error I received:

Error: The edge module has not been pre-compiled for node.js version v9.2.0. You
 must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.
    at determineVersion (. . .\node_modules\windows-certs\node_modules\edge\lib\edge.js:20:11)
    at Object.<anonymous> (. . .\node_modules\windows-certs\node_modules\edge\lib\edge.js:32:102)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (. . .\node_modules\windows-certs\index.js:1:74)
In the above stack I replaced actual file path by ellipsis. Other then that the error is all original.
Note that it directs poor user to your page, which does not have a solution.

**Comment by darkguy2008** [comment]
Same here for 9.3.0. II need to do a project with this library and there's no precompiled package nor concrete instructions on how to resolve this issue.

This should be given topmost priority. Any words on the progress of this?

Thanks

**Comment by agracio** [comment]
You can use `edge-js` fork that come pre compiled for Node.js 8.x and 9.x. https://github.com/agracio/edge-js

**Comment by darkguy2008** [comment]
@agracio thanks a lot for your answer. In my case I was using it with Electron so I used your ```electron-edge-js``` package and everything is going fine and dandy. Thanks for keeping it up to date!

I would've tried your instructions to manually build edge-js, but it's too complicated for me to understand and I'm making an app for an external client, so getting them to manually build edge-js just because the original maintainer doesn't do it or provide an easy way to do so is nosense :( it also requires VS to be installed as well and that's a bunch of requirements/scripts for just building a library. It's just my perception - I haven't tried to build it because I could not find any concrete documentation anyways, and I've spent around 2 days already trying to make it work with Electron, so thanks for your repo :)

**Comment by muithi** [comment]
Thank you @agracio 
I do not think I would have had engough time to downgrade my current Python installation to Python 2.7 and upgrade my VS to 2015 to build edge.js. Hell NO !
You have saved me endless struggles. 
Thanks a fortune. That is an awesome job you doing at **edge-js**. Gracias!

**Comment by DayBr3ak** [comment]
it's now as easy to do what Muithi said, by just doing 

    npm install --global --production windows-build-tools

then you can follow the readme to build your own version of edge

**Comment by andreszs** [comment]
I strongly agree with @borgold. I've just installed latest Node LTS version following Microsoft advice, and of course, the result is that I only get this error when trying to compile Apache Cordova apps now:

> 1>MSBUILD : cordova-build error : Error: The edge module has not been pre-compiled for node.js version v8.11.3. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.

Of course, I won't even try the instructions because now I must install MORE dependencies (Mono x64 and/or .NET Core - see below) and the README itself warns that this could easily fail, so it WILL fail. Reverting to Node 6 now, where things just worked without the need to waste hours trying to compile whatever was precompiled before.

**Congratulations for all developers who work hard to break stuff that already works, and constantly complicate other developer's lives in new and innovative ways. **

**Comment by agracio** [comment]
@andreszs Edge.js build process is very straightforward and is documented in it's README. It does not require Mono or .NET Core.
All you need is Python and build tools, you can see installation instruction above.
Build steps are in my previous comments to this issue.
And as per my previous comment, you can use also https://github.com/agracio/edge-js module instead that comes pre-compiled with all new Node.js versions.

**Comment by maxaqquepucho** [comment]
@darkguy2008 thank you so much for this library  electron-edge-js is very helpfull, is all that  i need.
i try to use and it is working very fine..

**Comment by kanso-git** [comment]
hello 
I am using edge-js to make node-native-printer work in windows 10 and everything works fine.
the problem is, i wanted to package my app into an executable file using pkg module from [https://npmjs.com/pkg](https://npmjs.com/pkg) but it seems that the pkg module is unable to manage the dependency between edge-js and node-native-prinnter .
I have tried many things but without any sucess.
I would appreciate if anyone can help me out to achieve my goal by packaging my app to an executable
any working project or detailed steps would be fine .

all the best and thank you in advance

**Comment by mushfau** [comment]
@kanso-git i'm having the exact same issue with node-native-printer and edge-js ..... were you able to find any solution?
