### ISSUE TITLE
No binary for 8.10.0 LTS

### ISSUE THREAD

**Issue by timonsku** [tjanczuk/edge#628]
When installing packages that use edge as a dependency I get the following error:
`Error: The edge module has not been pre-compiled for node.js version v8.10.0. You must build a custom version of edge.node. Please refer to https://github.com/tjanczuk/edge for building instructions.`

Building fails after installing all pre-requisites with a reference to Windows SDK 8.1 being missing. I'm on Windows 10. windows-build-tools is installed.

**Comment by tjanczuk** [comment]
Hello World!

**Comment by agracio** [comment]
Try using https://github.com/agracio/edge-js instead

**Comment by Bhawnananda** [comment]
+1

**Comment by Venryx** [comment]
Thanks, I'll be switching to the edge-js package for NodeJS 8/9/10 support.

@tjanczuk Is there a reason you don't want to update the library to support the newer NodeJS versions? I noticed the source code has support for NodeJS 8 now, but the latest npm package appears to be the older v7.

(I'm guessing it's just because you're short on time, but asking in case there's some other reason.)
