### ISSUE TITLE
Serious question

### ISSUE THREAD

**Issue by jfromaniello** [tjanczuk/edge#632]
What is the name of the first application you build when learning a new language?

**Comment by tjanczuk** [comment]
I always call mine `Test17`, in tribute to one of the college professors I had. She used a very simple naming pattern in her code, where types were `t` followed by a number, variables `v`, and so on. If you think about it, she was ahead of her time, since we are now using minification to achieve the same result. Programs are just not what they used to be.

**Comment by tjanczuk** [comment]
For example, here is my first serverless webtask created at https://webtask.io/make. You will notice the name is `Test17`:

**Comment by jfromaniello** [comment]
Hahaha!!! I was expecting “hello world”
